### ISSUE TITLE
合并类游戏算法

### ISSUE THREAD

**Issue by shizihang** [elecV2/QuantumultX-Tools#11]
大佬看到你写的《算法研究之合并类小游戏的最优购买问题》
，我有个思路希望可以帮到你。
先确定今天日期，比方说今天是1月5日，那么限定购买的最低等级joy为5级。确定当前joy的最低等级，确定剩余格子数，如果就剩一格，就买所拥有的最低等级的joy，如果大于等于两格就都买5级joy，然后合成。然后再确定等级和格子数，如此循环。

这样做的好处就是每个等级都会被买到，而且省去的麻烦的价格判断。假设每天获得的钱差不多，那么joy价格的上升会使得购买的数量下降，从而达到控制涨价的目的。这样就算某个joy价格奇高，也不会浪费什么钱，毕竟一个月就一天以某个joy为主。如果某个joy价格低，那么到以购买他为主的那一天，会自动买很多。这样就可以达到平衡价格的目的。

**Comment by elecV2** [comment]
也是一个不错的思路
