### ISSUE TITLE
dalao，百度的脚本在网页版贴吧上有点问题

### ISSUE THREAD

**Issue by ArsenicX** [elecV2/QuantumultX-Tools#13]
主要表现是如果用Safari打开网页版贴吧，不管是电脑版还是手机版浏览，都会看不到后面的回帖，只能看到前几楼
希望大佬能更新一下，谢谢🥺

**Comment by elecV2** [comment]
> 主要表现是如果用Safari打开网页版贴吧，不管是电脑版还是手机版浏览，都会看不到后面的回帖，只能看到前几楼
> 希望大佬能更新一下，谢谢🥺

不好意思，贴吧几年没用过了，以后有时间了研究一下（还是等别人比较靠谱

**Comment by ArsenicX** [comment]
> > 主要表现是如果用Safari打开网页版贴吧，不管是电脑版还是手机版浏览，都会看不到后面的回帖，只能看到前几楼
> > 希望大佬能更新一下，谢谢🥺
> 
> 不好意思，贴吧几年没用过了，以后有时间了研究一下（还是等别人比较靠谱

其他大佬的脚本的话，除了您这个我也再没找到类似的脚本
翻了好多脚本合集，最后也都追根溯源到您这里了😂

**Comment by elecV2** [comment]
因为没用，暂时先把这个 issue 关了。（如果有了解决方法，欢迎重开
