### ISSUE TITLE
pure 百度 会显示log的弹窗无法去除

### ISSUE THREAD

**Issue by FlechazoPh** [elecV2/QuantumultX-Tools#17]
请问怎么去除页面底部的日志弹窗，会阻挡点击事件导致按钮无法点击
如图：
![F696B078-96DD-4637-B3AB-4591FA890ABB](https://user-images.githubusercontent.com/94276146/148397550-496452ce-bac3-4a66-a257-53097a56f292.png)

**Comment by FlechazoPh** [comment]
使用百度以图搜图，依然会跳出百度搜索弹窗，无法使用：
![F9E23ED0-F9C1-41AA-A111-0D53829E3B51](https://user-images.githubusercontent.com/94276146/148402169-7a093ae7-bb39-4325-bedf-5f10e43a2513.png)

**Comment by elecV2** [comment]
手动删除脚本中 **tamperJS 日志输出** 那一段的代码。
其他页面无法使用的问题，手动调整 rewrite 匹配项。

(PS: 因为不怎么使用该脚本，所有基本不维护了
