### ISSUE TITLE
电信星播客签到送话费

### ISSUE THREAD

**Issue by taoziya-ya** [elecV2/QuantumultX-Tools#5]
大佬，电信星播客签到送话费，整一个吧！电信，发现，直播，右下悬浮领话费，签到7天15天30天，分别5元10元25元话费元10元25元话费

**Comment by elecV2** [comment]
> 大佬，电信星播客签到送话费，整一个吧！电信，发现，直播，右下悬浮领话费，签到7天15天30天，分别5元10元25元话费元10元25元话费

在写了。（新。。。
（可能不会有 
（直接抓包 http://xingboke.189.cn:8081/luntan/operation/add.do?type=signin 这条记录重放就好。
