### ISSUE TITLE
电信星播客脚本以及获取cookie问题

### ISSUE THREAD

**Issue by Wo1framalpha** [elecV2/QuantumultX-Tools#7]
① QuantumultX适用的星播客脚本（dxxbk.js）的注释中，设置定时任务的代码指向的是电信金豆换话费的脚本（dianx.js），而不是星播客脚本；
② 星播客脚本（dxxbk.js）获取cookie的条件是否和电信金豆换话费的脚本（dianx.js）的一致，为“金豆数量大于 400，以及上午 10 点前”？

**Comment by Wo1framalpha** [comment]
按“打开电信营业厅，我->(已)签到->2元话费（热门兑换）->立即兑换->兑换”这一流程获取cookie时，到点击2元话费会显示“未到兑换时间”，无法进一步获取cookie。

请问是否可以通过兑换其他物品获取cookie？

**Comment by Wo1framalpha** [comment]
成功兑换了3次2元话费，但没有提示成功获取cookie，执行星播客脚本（dxxbk.js）也提示没获取到cookie，请问该如何获取星播客脚本的cookie？

**Comment by elecV2** [comment]
> 成功兑换了3次2元话费，但没有提示成功获取cookie，执行星播客脚本（dxxbk.js）也提示没获取到cookie，请问该如何获取星播客脚本的cookie？

不好意思，脚本还没时间完成，不小心上传了。（脚本发布还是以频道通知为准）
