### ISSUE TITLE
去掉Endless Google的banner

### ISSUE THREAD

**Issue by xaver985** [elecV2/QuantumultX-Tools#8]
大佬你好，
能否去掉下部的banner，我觉得有些惹眼了
谢谢！
![A810B543-258C-4595-93BA-1DE3F878BE2A](https://user-images.githubusercontent.com/32983060/103019342-9fdb9e00-4581-11eb-9cc1-10b2af091b32.jpeg)

**Comment by FlechazoPh** [comment]
请问这个怎么去掉的？
